# Generated by Django 5.0.7 on 2024-09-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField(max_length=12)),
                ('coursename', models.CharField(max_length=100)),
                ('password', models.IntegerField(max_length=10)),
            ],
        ),
    ]
