# Generated by Django 5.0.7 on 2024-09-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiharDarogaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sid',
            field=models.IntegerField(default=0),
        ),
    ]
