# Generated by Django 5.0.7 on 2024-09-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiharDarogaApp', '0002_student_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sid',
        ),
    ]
