# Generated by Django 5.0.7 on 2024-09-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiharDarogaApp', '0004_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
